SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;

IF COL_LENGTH('dbo.HangHoa', 'MauSac') IS NULL EXEC(N'ALTER TABLE dbo.HangHoa ADD MauSac NVARCHAR(30) NULL;');
IF COL_LENGTH('dbo.HangHoa', 'ChatLieu') IS NULL EXEC(N'ALTER TABLE dbo.HangHoa ADD ChatLieu NVARCHAR(80) NULL;');
IF COL_LENGTH('dbo.HangHoa', 'KichThuoc') IS NULL EXEC(N'ALTER TABLE dbo.HangHoa ADD KichThuoc NVARCHAR(80) NULL;');
IF COL_LENGTH('dbo.HangHoa', 'BaoHanh') IS NULL EXEC(N'ALTER TABLE dbo.HangHoa ADD BaoHanh NVARCHAR(40) NULL;');
IF COL_LENGTH('dbo.HangHoa', 'PhongCach') IS NULL EXEC(N'ALTER TABLE dbo.HangHoa ADD PhongCach NVARCHAR(50) NULL;');
GO

BEGIN TRY
    BEGIN TRAN;

    SET IDENTITY_INSERT dbo.Loai ON;
    MERGE dbo.Loai AS target
    USING (VALUES
        (1, N'Sofas & Lounge Seating', N'sofas-lounge-seating', N'Distinct sofa and lounge scenes for living rooms, apartments and relaxed social spaces.', N'cat-sofas.jpg'),
        (2, N'Dining Chairs & Sets', N'dining-chairs-sets', N'Dining chairs and dining-room furniture for everyday meals and hosted gatherings.', N'cat-dining-chairs.jpg'),
        (3, N'Stools & Bar Chairs', N'stools-bar-chairs', N'Counter stools, bar chairs and compact side stools for flexible seating.', N'cat-stools-bar.jpg'),
        (4, N'Rocking Chairs', N'rocking-chairs', N'Soft rockers and slow-living seating for bedrooms, nurseries and quiet corners.', N'cat-rocking-chairs.jpg'),
        (5, N'Coffee Tables', N'coffee-tables', N'Coffee tables and central living-room surfaces for styling, storage and daily use.', N'cat-coffee-tables.jpg'),
        (6, N'Desks & Worktables', N'desks-worktables', N'Compact desks and worktables for home office, laptop work and flexible study zones.', N'cat-desks-worktables.jpg'),
        (7, N'Cabinets & Storage', N'cabinets-storage', N'Storage cabinets, sideboards and enclosed storage furniture for organized interiors.', N'cat-cabinets-storage.jpg'),
        (8, N'Baskets & Soft Storage', N'baskets-soft-storage', N'Woven baskets and flexible soft storage accents for blankets, magazines and small essentials.', N'cat-baskets-storage.jpg'),
        (9, N'Planters & Vases', N'planters-vases', N'Indoor planters, ceramic vases and botanical decor for shelves, desks and tabletop styling.', N'cat-planters-greenery.jpg'),
        (10, N'Lighting', N'lighting', N'Pendant, floor and table lamps for ambient modern lighting.', N'cat-lighting.jpg'),
        (11, N'Home Audio', N'home-audio', N'Speakers and audio pieces for design-led listening corners and desktop setups.', N'cat-home-audio.jpg'),
        (12, N'Travel Suitcases', N'travel-suitcases', N'Carry-on luggage, weekend trolleys and travel-ready suitcases for modern trips.', N'cat-travel-suitcases.jpg'),
        (13, N'Photography Gear', N'photography-gear', N'Compact cameras and everyday photography gear with product-focused presentation.', N'cat-photography-gear.jpg'),
        (14, N'Laptops & Computing', N'laptops-computing', N'Portable computers and everyday productivity devices for work and study.', N'cat-laptops-computing.jpg'),
        (15, N'Watches & Timepieces', N'watches-timepieces', N'Classic watches and durable timepieces with gift-ready presentation.', N'cat-watches-timepieces.jpg'),
        (16, N'Television & Media', N'television-media', N'TV and media-room products for entertainment-focused living spaces.', N'cat-television-media.jpg'),
        (17, N'Decor Objects', N'decor-objects', N'Statement decorative objects, table lamps and accent pieces for styled interiors.', N'cat-decor-objects.jpg'),
        (18, N'Wall Art', N'wall-art', N'Framed artwork and graphic wall pieces for living rooms, bedrooms and creative workspaces.', N'cat-wall-art.jpg'),
        (19, N'Console & Entry Tables', N'console-entry-tables', N'Slim console tables and entryway surfaces for hallways, mirrors, keys and styled decor.', N'cat-console-entry.jpg')
    ) AS src (MaLoai, TenLoai, TenLoaiAlias, MoTa, Hinh)
    ON target.MaLoai = src.MaLoai
    WHEN MATCHED THEN UPDATE SET TenLoai=src.TenLoai, TenLoaiAlias=src.TenLoaiAlias, MoTa=src.MoTa, Hinh=src.Hinh
    WHEN NOT MATCHED BY TARGET THEN INSERT (MaLoai, TenLoai, TenLoaiAlias, MoTa, Hinh) VALUES (src.MaLoai, src.TenLoai, src.TenLoaiAlias, src.MoTa, src.Hinh);
    SET IDENTITY_INSERT dbo.Loai OFF;

    MERGE dbo.NhaCungCap AS target
    USING (VALUES
        (N'NCC001', N'Atelier Living', N'ncc-saoviet.png', N'John Nguyen', N'atelier.living@hshop.local', N'0901000001', N'District 1, HCMC', N'Curated supplier for sofas, tables and premium home styling items.'),
        (N'NCC002', N'Urban Utility', N'ncc-minhan.png', N'Tracy Tran', N'urban.utility@hshop.local', N'0901000002', N'Thu Duc, HCMC', N'Supplier of functional storage, travel-ready goods and compact productivity products.'),
        (N'NCC003', N'Lifestyle Edit', N'ncc-vinastyle.png', N'Chris Le', N'lifestyle.edit@hshop.local', N'0901000003', N'Binh Thanh, HCMC', N'Supplier of curated lifestyle accessories, decor objects, watches and baskets.'),
        (N'NCC004', N'Studio Tech House', N'ncc-vinastyle.png', N'Diana Pham', N'studio.tech@hshop.local', N'0901000004', N'District 7, HCMC', N'Supplier of lighting, audio, TV, computing and imaging products for a broader lifestyle catalog.')
    ) AS src (MaNCC, TenCongTy, Logo, NguoiLienLac, Email, DienThoai, DiaChi, MoTa)
    ON target.MaNCC = src.MaNCC
    WHEN MATCHED THEN UPDATE SET TenCongTy=src.TenCongTy, Logo=src.Logo, NguoiLienLac=src.NguoiLienLac, Email=src.Email, DienThoai=src.DienThoai, DiaChi=src.DiaChi, MoTa=src.MoTa
    WHEN NOT MATCHED BY TARGET THEN INSERT (MaNCC, TenCongTy, Logo, NguoiLienLac, Email, DienThoai, DiaChi, MoTa) VALUES (src.MaNCC, src.TenCongTy, src.Logo, src.NguoiLienLac, src.Email, src.DienThoai, src.DiaChi, src.MoTa);

    MERGE dbo.TrangThai AS target
    USING (VALUES
        (0, N'New', N'Order has been created.'),
        (1, N'Pending Confirmation', N'Order is waiting for staff confirmation.'),
        (2, N'Shipping', N'Order is being delivered.'),
        (3, N'Completed', N'Order has been delivered successfully.'),
        (4, N'Cancelled', N'Order has been cancelled.')
    ) AS src (MaTrangThai, TenTrangThai, MoTa)
    ON target.MaTrangThai = src.MaTrangThai
    WHEN MATCHED THEN UPDATE SET TenTrangThai=src.TenTrangThai, MoTa=src.MoTa
    WHEN NOT MATCHED BY TARGET THEN INSERT (MaTrangThai, TenTrangThai, MoTa) VALUES (src.MaTrangThai, src.TenTrangThai, src.MoTa);

    SET IDENTITY_INSERT dbo.HangHoa ON;
    MERGE dbo.HangHoa AS target
    USING (VALUES
        (1, N'Cloud Modular Sofa', N'cloud-modular-sofa', 1, N'Soft modular living-room sofa', 18990000.0, N'web-sofa-01.jpg', CAST('2026-01-05' AS datetime), 0.0, 120, N'Generous modular sofa scene for living rooms that need relaxed comfort, layered cushions and a warm social focal point.', N'NCC001', 8, N'Warm neutral', N'Upholstered fabric, hardwood frame', N'Approx. W260 x D95 x H82 cm', N'24 tháng', N'Contemporary Living'),
        (2, N'Urban Apartment Couch', N'urban-apartment-couch', 1, N'Compact apartment couch', 12990000.0, N'web-sofa-02.jpg', CAST('2026-01-08' AS datetime), 5.0, 108, N'Modern apartment couch sized for compact homes, rental interiors and clean everyday lounge layouts.', N'NCC001', 10, N'Gray', N'Textile upholstery, wood frame', N'Approx. W210 x D88 x H80 cm', N'24 tháng', N'Urban Minimal'),
        (3, N'Solid Wood Coffee Table', N'solid-wood-coffee-table', 5, N'Wood coffee table for living room', 6590000.0, N'web-coffee-table-01.jpg', CAST('2026-01-12' AS datetime), 0.0, 94, N'Solid wood coffee table styled in a finished living-room scene, suitable for decor, books and daily entertaining.', N'NCC001', 12, N'Natural wood', N'Solid wood top, sealed finish', N'Approx. W120 x D60 x H42 cm', N'24 tháng', N'Warm Modern'),
        (4, N'Recycled Wood Dining Set', N'recycled-wood-dining-set', 2, N'Dining room set with chairs', 15990000.0, N'web-dining-room-01.jpg', CAST('2026-01-16' AS datetime), 8.0, 87, N'Dining set with a recycled wood ceiling scene, balancing natural texture and practical seating for family meals.', N'NCC001', 6, N'Natural wood', N'Wood dining table, upholstered chairs', N'Table approx. W180 x D90 cm', N'24 tháng', N'Rustic Modern'),
        (5, N'Media Console TV Setup', N'media-console-tv-setup', 16, N'Living-room TV and media setup', 14990000.0, N'web-tv-room-01.jpg', CAST('2026-01-20' AS datetime), 6.0, 132, N'Television and media console setup for entertainment-focused living rooms with clean cable-friendly styling.', N'NCC004', 9, N'Black / Walnut', N'LED TV, media console, mixed materials', N'55 inch class TV setup', N'24 tháng', N'Media Lounge'),
        (6, N'Studio Monitor Speaker Pair', N'studio-monitor-speaker-pair', 11, N'Desktop speaker pair', 3290000.0, N'web-speaker-01.jpg', CAST('2026-01-24' AS datetime), 0.0, 76, N'Desktop audio speaker pair for home office, studio corners and compact listening setups.', N'NCC004', 16, N'Black', N'Active speaker housings, desktop stands', N'Pair, compact desktop size', N'12 tháng', N'Studio Audio'),
        (7, N'Arc Floor Lamp Apartment', N'arc-floor-lamp-apartment', 10, N'Floor lamp in apartment scene', 3890000.0, N'web-floor-lamp-01.jpg', CAST('2026-01-28' AS datetime), 4.0, 69, N'Floor lamp shown in a finished apartment interior, ideal for soft ambient light beside sofas or reading chairs.', N'NCC004', 11, N'Black / Warm white', N'Metal frame, fabric shade', N'Approx. H160 cm', N'18 tháng', N'Ambient Lighting'),
        (8, N'Peacock Table Lamp', N'peacock-table-lamp', 17, N'Decorative table lamp', 2890000.0, N'web-table-lamp-01.jpg', CAST('2026-02-01' AS datetime), 0.0, 58, N'Decorative table lamp with detailed glasswork, best for consoles, sideboards and statement accent corners.', N'NCC003', 7, N'Multicolor', N'Stained glass shade, metal base', N'Approx. H48 cm', N'12 tháng', N'Statement Decor'),
        (9, N'Ceramic Decor Vase', N'ceramic-decor-vase', 9, N'Ceramic decorative vase', 1290000.0, N'web-vase-01.jpg', CAST('2026-02-05' AS datetime), 0.0, 52, N'Ceramic vase for shelves, console tops and styled tables where one strong decorative object is enough.', N'NCC003', 18, N'Warm yellow', N'Glazed ceramic', N'Approx. H35 cm', N'12 tháng', N'Decor Accent'),
        (10, N'Framed Line Art Print', N'framed-line-art-print', 18, N'Framed wall art print', 990000.0, N'web-wall-art-01.jpg', CAST('2026-02-09' AS datetime), 0.0, 47, N'Framed line art print for living-room, bedroom or creative workspace walls with a clean contemporary tone.', N'NCC003', 20, N'Black / White', N'Printed art paper, slim frame', N'Approx. 50 x 70 cm', N'12 tháng', N'Minimal Wall Art'),
        (11, N'Window Side Rocker', N'window-side-rocker', 4, N'Window-side rocking chair', 4890000.0, N'rocking-chair-03.jpg', CAST('2026-02-13' AS datetime), 0.0, 72, N'Window-side rocker that turns unused corners into soft reading nooks.', N'NCC004', 7, N'White', N'Fabric seat, wood rocker base', N'W69 x D90 x H97 cm', N'24 tháng', N'Calm Reading Nook'),
        (12, N'White Console Table', N'white-console-table', 19, N'Minimal white console table', 2950000.0, N'web-entry-table-01.jpg', CAST('2026-02-17' AS datetime), 0.0, 67, N'Slim white console table suitable for entry walls, hallways and decorative staging surfaces with a distinct hallway image.', N'NCC001', 10, N'White / wood', N'Console table, hallway styling', N'Entryway scale', N'24 tháng', N'Modern Entryway'),
        (13, N'Minimal Console Desk', N'minimal-console-desk', 6, N'Minimal console desk', 3190000.0, N'web-white-cabinet-01.jpg', CAST('2026-02-21' AS datetime), 5.0, 61, N'Compact desk-like storage console for laptop work or apartment drop zones, using a distinct white furniture scene.', N'NCC002', 8, N'White', N'Engineered wood cabinet/desk surface', N'Compact furniture scale', N'24 tháng', N'Apartment Workspace'),
        (14, N'Botanical Entry Console', N'botanical-entry-console', 19, N'Entry console with greenery styling', 3490000.0, N'cabinet-plant-01.jpg', CAST('2026-02-25' AS datetime), 7.0, 52, N'Botanical entry storage surface with visible greenery styling and a distinct cabinet-console look.', N'NCC003', 6, N'White', N'Engineered wood, easy-clean painted finish', N'Console/cabinet scale', N'24 tháng', N'Botanical Modern'),
        (15, N'Minimal Side Cabinet', N'minimal-side-cabinet', 7, N'Minimal side cabinet', 4090000.0, N'lux-duncan-storage-interior.jpg', CAST('2026-03-01' AS datetime), 6.0, 39, N'Side cabinet for hallway or dining wall storage with understated minimalist lines in a distinct storage interior.', N'NCC001', 5, N'Walnut / neutral', N'Wood veneer cabinet, slim profile frame', N'Storage wall / console scale', N'24 tháng', N'Minimal Dining Storage'),
        (16, N'White Storage Cabinet', N'white-storage-cabinet', 7, N'White storage cabinet', 3890000.0, N'web-white-cabinet-01.jpg', CAST('2026-03-05' AS datetime), 0.0, 48, N'White storage cabinet shown as a distinct interior storage product instead of repeating the side-cabinet plant image.', N'NCC002', 8, N'White', N'Engineered wood cabinet, painted doors', N'Cabinet / sideboard scale', N'24 tháng', N'Gallery Storage'),
        (18, N'Succulent Accent Pot', N'succulent-accent-pot', 9, N'Small succulent accent pot', 690000.0, N'succulent-pot-03.jpg', CAST('2026-03-13' AS datetime), 0.0, 42, N'Compact succulent accent pot for shelves, small consoles and styled tabletop corners.', N'NCC003', 18, N'Green / beige', N'Live-style succulent, ceramic-look pot', N'Approx. H18 cm', N'6 tháng', N'Tabletop Greenery'),
        (19, N'Ceramic Succulent Planter', N'ceramic-succulent-planter', 9, N'Ceramic succulent planter', 790000.0, N'web-desk-succulent-01.jpg', CAST('2026-03-17' AS datetime), 0.0, 40, N'Ceramic succulent planter with a distinct close-up plant form, suitable for desks and shelf styling.', N'NCC003', 16, N'Green / terracotta', N'Ceramic pot, succulent greenery', N'Approx. H16 cm', N'6 tháng', N'Desk Greenery'),
        (20, N'Oak Top Succulent Pot', N'oak-top-succulent-pot', 9, N'Oak-top succulent pot', 890000.0, N'lux-modern-room-succulent.jpg', CAST('2026-03-21' AS datetime), 5.0, 36, N'Modern succulent planter scene with a warmer architectural feel for oak, stone and wood interiors.', N'NCC003', 14, N'Green / natural', N'Ceramic planter, botanical greenery', N'Tabletop accent size', N'6 tháng', N'Natural Modern'),
        (21, N'Small Desk Succulent', N'small-desk-succulent', 9, N'Small desk succulent', 590000.0, N'succulent-pot-03.jpg', CAST('2026-03-25' AS datetime), 0.0, 33, N'Small desk succulent for work corners that need a fresh, low-maintenance green accent.', N'NCC003', 22, N'Green / beige', N'Succulent, ceramic-look pot', N'Approx. H18 cm', N'6 tháng', N'Workspace Greenery'),
        (22, N'Aloe Pedestal Planter', N'aloe-pedestal-planter', 9, N'Aloe pedestal planter', 1190000.0, N'aloe-planter-01.jpg', CAST('2026-03-29' AS datetime), 0.0, 31, N'Aloe planter with a full visible plant-and-pot silhouette for console tops, shelves and plant stands.', N'NCC003', 12, N'Green / white', N'Aloe plant, ceramic planter', N'Approx. H38 cm', N'6 tháng', N'Modern Botanical'),
        (23, N'Modern Aloe Planter', N'modern-aloe-planter', 9, N'Modern aloe planter', 990000.0, N'web-aloe-planter-01.jpg', CAST('2026-04-02' AS datetime), 0.0, 29, N'Modern aloe planter in a distinct balcony plant scene so it no longer repeats the local pedestal planter crop.', N'NCC003', 15, N'Green / white', N'Aloe plant, ceramic planter', N'Balcony planter scale', N'6 tháng', N'Clean Botanical'),
        (24, N'Pendant Light Trio', N'pendant-light-trio', 10, N'Trio of pendant lights', 2490000.0, N'pendant-light-01.jpg', CAST('2026-04-06' AS datetime), 0.0, 62, N'Trio of warm pendant lights with clear product focus for dining counters and intimate kitchen islands.', N'NCC004', 11, N'Graphite / amber', N'Metal shades, warm LED-compatible bulbs', N'3-light cluster', N'24 tháng', N'Warm Industrial'),
        (25, N'Warm Dining Pendant Set', N'warm-dining-pendant-set', 10, N'Warm dining pendant set', 2890000.0, N'lux-pendant-white-kitchen.jpg', CAST('2026-04-10' AS datetime), 5.0, 57, N'Warm dining pendant set shown in a real kitchen setting, useful for buyers comparing island and dining-room scale.', N'NCC004', 9, N'Warm white', N'Metal fixtures, LED-compatible lights', N'Multiple pendant set', N'24 tháng', N'Kitchen Modern'),
        (26, N'Graphite Pendant Cluster', N'graphite-pendant-cluster', 10, N'Graphite pendant cluster', 3190000.0, N'web-pendant-cluster-01.jpg', CAST('2026-04-14' AS datetime), 0.0, 55, N'Graphite pendant light cluster with a more architectural composition for bars, dining zones and layered lighting.', N'NCC004', 8, N'Graphite', N'Metal pendant cluster, LED-compatible', N'Cluster fixture', N'24 tháng', N'Architectural Lighting'),
        (27, N'Round Wall Speaker', N'round-wall-speaker', 11, N'Round wall speaker', 1790000.0, N'wall-speaker-02.jpg', CAST('2026-04-18' AS datetime), 0.0, 49, N'Round minimal wall speaker with strap detail, selected as the cleanest product-focused view in the local set.', N'NCC004', 17, N'Tan / gray', N'Compact speaker body, hanging strap', N'Wall-mounted compact size', N'12 tháng', N'Minimal Audio'),
        (28, N'Minimal Hanging Speaker', N'minimal-hanging-speaker', 11, N'Minimal hanging speaker', 1990000.0, N'web-hanging-speaker-01.jpg', CAST('2026-04-22' AS datetime), 5.0, 44, N'Minimal wall speaker shown in an interior context so this audio product no longer duplicates the round product shot.', N'NCC004', 13, N'White / neutral', N'In-wall or hanging speaker system', N'Compact wall audio', N'12 tháng', N'Integrated Audio'),
        (29, N'Accent Chair with Throw', N'accent-chair-with-throw', 1, N'Accent chair with throw', 3690000.0, N'accent-chair-05.jpg', CAST('2026-04-26' AS datetime), 0.0, 53, N'Accent chair with a soft throw-style presentation, kept as the clearest close product view from the duplicate chair group.', N'NCC001', 10, N'White / natural', N'Fabric seat, wood legs', N'W62 x D64 x H78 cm', N'24 tháng', N'Cozy Accent'),
        (30, N'Cozy Reading Chair', N'cozy-reading-chair', 1, N'Cozy reading chair', 6890000.0, N'lux-ray-lounge-chair.jpg', CAST('2026-04-30' AS datetime), 0.0, 48, N'Sculptural lounge chair for a distinct reading-corner product, replacing the repeated white accent-chair image.', N'NCC001', 7, N'Blue / warm neutral', N'Premium upholstered lounge chair', N'Reading-corner scale', N'24 tháng', N'Statement Reading'),
        (31, N'Soft Lounge Rocker', N'soft-lounge-rocker', 4, N'Soft lounge rocker', 5290000.0, N'rocking-chair-03.jpg', CAST('2026-05-04' AS datetime), 6.0, 38, N'Soft rocker for calm corners, nurseries and window-side reading spaces.', N'NCC004', 6, N'White', N'Fabric seat, wood rocker base', N'W69 x D90 x H97 cm', N'24 tháng', N'Calm Rocking'),
        (32, N'Slim Entry Table', N'slim-entry-table', 19, N'Slim entry table', 3150000.0, N'console-mirror-02-alt.jpg', CAST('2026-05-08' AS datetime), 0.0, 46, N'Slim entry table with clean white console styling and greenery.', N'NCC001', 9, N'White', N'Console table, hallway styling', N'W120 x D36 x H80 cm', N'24 tháng', N'Entry Utility'),
        (33, N'Mirror-Styled Console', N'mirror-styled-console', 19, N'Mirror-styled console', 3490000.0, N'web-entry-table-01.jpg', CAST('2026-05-12' AS datetime), 5.0, 41, N'Mirror-styled console/entry table in a hallway setting, separated from the local console duplicate group.', N'NCC003', 8, N'White / wood', N'Console table, hallway styling', N'Entryway scale', N'24 tháng', N'Mirror Entry'),
        (34, N'Woven Storage Basket', N'woven-storage-basket', 8, N'Woven basket with soft textile', 2690000.0, N'storage-basket-03.jpg', CAST('2026-05-16' AS datetime), 0.0, 34, N'Woven storage basket with a soft textile liner, suitable for cozy corners, blankets and styled floor storage.', N'NCC003', 6, N'Natural', N'Handwoven basket body, removable textile liner', N'W48 x D48 x H42 cm', N'12 tháng', N'Cozy Storage'),
        (35, N'Compact Side Stool', N'compact-side-stool', 3, N'Compact side stool', 1290000.0, N'web-side-stool-01.jpg', CAST('2026-05-20' AS datetime), 0.0, 39, N'Compact side stool with a lower casual profile, replacing the duplicated counter-stool view for a truer side-stool product.', N'NCC002', 15, N'Natural / black', N'Wood or laminate seat, metal support', N'Side-stool height', N'12 tháng', N'Compact Utility'),
        (36, N'Bookrest Bar Stool', N'bookrest-bar-stool', 3, N'Bookrest bar stool', 2290000.0, N'lux-modern-bar-stools.jpg', CAST('2026-05-24' AS datetime), 5.0, 43, N'Bookrest-style bar stool scene with a counter-height context, replacing the repeated transparent stool with a distinct bar seating setup.', N'NCC002', 10, N'Black / natural', N'Solid wood / metal frame', N'Counter / bar height', N'12 tháng', N'Modern Bar'),
        (37, N'Carry-On Cabin Suitcase', N'carry-on-cabin-suitcase', 12, N'Compact carry-on luggage', 3290000.0, N'31ioCUUFnoL.jpg', CAST('2026-05-28' AS datetime), 0.0, 18, N'Compact hard-shell suitcase sized for short trips, quick check-ins and neat travel organization.', N'NCC002', 14, N'Black', N'ABS shell, telescopic handle', N'20 inch carry-on', N'12 tháng', N'Urban Travel'),
        (38, N'Hard-Shell Weekend Suitcase', N'hard-shell-weekend-suitcase', 12, N'Weekend spinner suitcase', 3490000.0, N'31hCgES5GXL._AA300_.jpg', CAST('2026-06-01' AS datetime), 5.0, 21, N'Structured weekend suitcase with a clean profile for fast departures and lightweight packing.', N'NCC002', 11, N'Silver', N'Hard-shell body, spinner wheels', N'22 inch cabin size', N'12 tháng', N'Minimal Travel'),
        (39, N'Travel Duffel Holdall', N'travel-duffel-holdall', 12, N'Soft travel holdall', 2190000.0, N'31yxRemzRLL._SS350_ (1).jpg', CAST('2026-06-05' AS datetime), 0.0, 17, N'Soft-sided travel holdall for overnight stays, road trips and flexible packing needs.', N'NCC003', 13, N'Black', N'Textile shell, shoulder strap', N'50L capacity', N'12 tháng', N'Weekend Utility'),
        (40, N'Red Rolling Suitcase', N'red-rolling-suitcase', 12, N'Red trolley luggage', 3590000.0, N'41Z43OmFHjL._SX342_.jpg', CAST('2026-06-09' AS datetime), 8.0, 24, N'Red rolling suitcase that stands out at baggage claim while keeping travel essentials protected.', N'NCC002', 9, N'Red', N'Polycarbonate shell, spinner base', N'24 inch medium', N'12 tháng', N'Bold Travel'),
        (41, N'Graphite Spinner Luggage', N'graphite-spinner-luggage', 12, N'Graphite travel suitcase', 3890000.0, N'51JhyHtnEgL._SL1001_.jpg', CAST('2026-06-13' AS datetime), 0.0, 19, N'Graphite spinner luggage with a streamlined shell for smooth airport movement and durable use.', N'NCC002', 8, N'Graphite', N'Hard-shell shell, spinner wheels', N'26 inch checked', N'12 tháng', N'Modern Transit'),
        (42, N'Lavender Travel Trolley', N'lavender-travel-trolley', 12, N'Lavender trolley suitcase', 3690000.0, N'71bJrFAys9L._SL1280_.jpg', CAST('2026-06-17' AS datetime), 7.0, 16, N'Lavender travel trolley with a playful colorway and tidy storage for weekend and holiday travel.', N'NCC003', 7, N'Lavender', N'ABS shell, telescoping handle', N'24 inch spinner', N'12 tháng', N'Color Travel'),
        (43, N'Compact Travel Camera', N'compact-travel-camera', 13, N'Portable compact camera', 2890000.0, N'41ZE9SmWdzL._SL500_AA300_.jpg', CAST('2026-06-21' AS datetime), 0.0, 27, N'Pocket-friendly compact camera for everyday snapshots, travel journals and quick family moments.', N'NCC004', 10, N'Black', N'Compact digital camera, fixed lens', N'Pocket size', N'12 tháng', N'Travel Friendly'),
        (44, N'Mirrorless Street Camera', N'mirrorless-street-camera', 13, N'Street-ready compact camera', 4590000.0, N'41sl3FN6NpL.jpg', CAST('2026-06-25' AS datetime), 5.0, 22, N'Street-ready compact camera with a simple body and fast access for casual photography sessions.', N'NCC004', 9, N'Black', N'Digital body, compact zoom lens', N'Handheld compact', N'12 tháng', N'Street Capture'),
        (45, N'Aqua Compact Camera', N'aqua-compact-camera', 13, N'Aqua point-and-shoot camera', 3090000.0, N'41w4TlVPhGL.jpg', CAST('2026-06-29' AS datetime), 0.0, 18, N'Aqua compact camera with a cheerful finish for gifting, travel and everyday carry.', N'NCC004', 11, N'Aqua', N'Point-and-shoot body, wrist strap', N'Pocket size', N'12 tháng', N'Color Capture'),
        (46, N'Lumix Pocket Camera', N'lumix-pocket-camera', 13, N'Lumix point-and-shoot', 3390000.0, N'51pvLIvb6ZL._SL500_AA300_.jpg', CAST('2026-07-03' AS datetime), 10.0, 23, N'Pocket-sized Lumix camera for quick travel shots and lightweight day-to-day photography.', N'NCC004', 8, N'Black', N'Compact digital camera, fixed zoom', N'Pocket size', N'12 tháng', N'Everyday Capture'),
        (47, N'Silver Everyday Laptop', N'silver-everyday-laptop', 14, N'Silver everyday laptop', 12990000.0, N'41qlcUEhNmL._SL500_AA300_.jpg', CAST('2026-07-07' AS datetime), 0.0, 32, N'Silver everyday laptop built for study, browser work, admin tasks and portable productivity.', N'NCC002', 6, N'Silver', N'Aluminum-look shell, integrated keyboard', N'14 inch class', N'12 tháng', N'Everyday Computing'),
        (48, N'Business Notebook Laptop', N'business-notebook-laptop', 14, N'Business notebook laptop', 13990000.0, N'41riQRGf-6L._SL500_AA300_.jpg', CAST('2026-07-11' AS datetime), 4.0, 29, N'Business notebook laptop with a no-fuss profile for documents, meetings and desk work.', N'NCC002', 5, N'Black', N'Notebook chassis, full keyboard', N'15 inch class', N'12 tháng', N'Office Ready'),
        (49, N'Classic Silver Wristwatch', N'classic-silver-wristwatch', 15, N'Classic silver watch', 2590000.0, N'41yh1vBmqsL._SL500_AA300_.jpg', CAST('2026-07-15' AS datetime), 0.0, 33, N'Classic silver wristwatch with a clean dial and polished finish for gifting or daily wear.', N'NCC003', 15, N'Silver', N'Metal bracelet, analog movement', N'42 mm case', N'12 tháng', N'Gift Ready'),
        (50, N'Rugged Black Sports Watch', N'rugged-black-sports-watch', 15, N'Rugged sports timepiece', 2990000.0, N'51uJ-pWfc9L._SL500_AA300_.jpg', CAST('2026-07-19' AS datetime), 6.0, 35, N'Rugged black sports watch designed for active routines, casual wear and durable daily use.', N'NCC003', 14, N'Black', N'Resin case, sport strap', N'45 mm case', N'12 tháng', N'Active Utility'),
        (51, N'Gallery White Sofa', N'gallery-white-sofa', 1, N'White sofa in refined gallery-style living room', 21990000.0, N'lux-sofa-white-gallery.jpg', CAST('2026-08-01' AS datetime), 0.0, 127, N'White sofa in refined gallery-style living room sourced as a distinct luxury catalog image so the collection no longer repeats near-identical product photos.', N'NCC001', 15, N'Warm neutral', N'Premium upholstery, hardwood frame', N'Living-room scale', N'24 tháng', N'Luxury Showroom'),
        (52, N'Black Leather Lounge Set', N'black-leather-lounge-set', 1, N'Black leather lounge with glass table and mirror', 19990000.0, N'lux-black-leather-lounge.jpg', CAST('2026-08-02' AS datetime), 6.0, 44, N'Black leather lounge with glass table and mirror sourced as a distinct luxury catalog image so the collection no longer repeats near-identical product photos.', N'NCC001', 18, N'Warm neutral', N'Premium upholstery, hardwood frame', N'Living-room scale', N'24 tháng', N'Luxury Showroom'),
        (53, N'Gold Accent Dining Room', N'gold-accent-dining-room', 2, N'Gold-accent dining room with ornate ceiling', 24990000.0, N'lux-gold-dining-room.jpg', CAST('2026-08-03' AS datetime), 0.0, 51, N'Elegant dining room with gold chairs and ornate ceiling sourced as a distinct luxury catalog image so the collection no longer repeats near-identical product photos.', N'NCC001', 21, N'Walnut / cream', N'Wood dining table, upholstered chairs', N'Dining-room set', N'24 tháng', N'Luxury Showroom'),
        (54, N'Warm Modern Dining Area', N'warm-modern-dining-area', 2, N'Modern dining area with stylish table and chairs', 17990000.0, N'lux-modern-dining-area.jpg', CAST('2026-08-04' AS datetime), 0.0, 58, N'Modern dining area with stylish table and chairs sourced as a distinct luxury catalog image so the collection no longer repeats near-identical product photos.', N'NCC001', 24, N'Walnut / cream', N'Wood dining table, upholstered chairs', N'Dining-room set', N'24 tháng', N'Luxury Showroom'),
        (55, N'Minimal Counter Stool', N'minimal-counter-stool', 3, N'Minimal transparent counter stool', 2290000.0, N'counter-stool-04.jpg', CAST('2026-08-05' AS datetime), 5.0, 65, N'Minimal counter stool using the sharpest clean local product image from the duplicate stool set.', N'NCC002', 27, N'Clear / natural', N'Acrylic seat, compact counter-height frame', N'Counter height', N'12 tháng', N'Minimal Counter'),
        (56, N'Fruitwood Bar Stool Set', N'fruitwood-bar-stool-set', 3, N'Warm fruitwood stools for elevated bar seating', 2690000.0, N'lux-fruitwood-bar-stools.jpg', CAST('2026-08-06' AS datetime), 8.0, 72, N'Warm fruitwood stools for elevated bar seating sourced as a distinct luxury catalog image so the collection no longer repeats near-identical product photos.', N'NCC002', 6, N'Black / natural', N'Solid wood / metal frame', N'Counter / bar height', N'12 tháng', N'Luxury Showroom'),
        (57, N'Rustic Wood Coffee Table', N'rustic-wood-coffee-table', 5, N'Rustic coffee table with warm natural character', 5990000.0, N'lux-rustic-coffee-table.jpg', CAST('2026-08-07' AS datetime), 0.0, 79, N'Rustic coffee table with warm natural character sourced as a distinct luxury catalog image so the collection no longer repeats near-identical product photos.', N'NCC001', 9, N'Natural wood', N'Wood or glass tabletop, sculptural base', N'Approx. W120 x D70 cm', N'24 tháng', N'Luxury Showroom'),
        (58, N'Sculptural Glass Coffee Table', N'sculptural-glass-coffee-table', 5, N'Sculptural glass coffee table for lounges', 7490000.0, N'lux-noguchi-coffee-table.jpg', CAST('2026-08-08' AS datetime), 6.0, 86, N'Sculptural glass coffee table for design-led lounges sourced as a distinct luxury catalog image so the collection no longer repeats near-identical product photos.', N'NCC001', 12, N'Natural wood', N'Wood or glass tabletop, sculptural base', N'Approx. W120 x D70 cm', N'24 tháng', N'Luxury Showroom'),
        (59, N'Leaf Rug Media Lounge', N'leaf-rug-media-lounge', 16, N'Modern TV lounge with vibrant rug', 15990000.0, N'lux-tv-leaf-rug-room.jpg', CAST('2026-08-09' AS datetime), 0.0, 93, N'Modern TV lounge with vibrant rug and white furniture sourced as a distinct luxury catalog image so the collection no longer repeats near-identical product photos.', N'NCC004', 15, N'Black / wood', N'LED TV, media console, mixed materials', N'55 inch class setup', N'24 tháng', N'Luxury Showroom'),
        (60, N'Wood Media Console TV', N'wood-media-console-tv', 16, N'Large flat-screen TV on warm wooden media console', 16990000.0, N'lux-wood-media-console.jpg', CAST('2026-08-10' AS datetime), 0.0, 100, N'Large flat-screen TV on warm wooden media console sourced as a distinct luxury catalog image so the collection no longer repeats near-identical product photos.', N'NCC004', 18, N'Black / wood', N'LED TV, media console, mixed materials', N'55 inch class setup', N'24 tháng', N'Luxury Showroom'),
        (61, N'Vaulted Pendant Kitchen', N'vaulted-pendant-kitchen', 10, N'Modern kitchen with island pendant lighting', 3490000.0, N'lux-pendant-white-kitchen.jpg', CAST('2026-08-11' AS datetime), 5.0, 107, N'Modern kitchen with island pendant lighting sourced as a distinct luxury catalog image so the collection no longer repeats near-identical product photos.', N'NCC004', 21, N'Warm white', N'Metal fixture, warm LED-compatible light', N'Fixture or table-lamp scale', N'24 tháng', N'Luxury Showroom'),
        (62, N'Gray Table Lamp', N'gray-table-lamp', 10, N'Soft gray table lamp for bedside styling', 1790000.0, N'lux-gray-table-lamp.jpg', CAST('2026-08-12' AS datetime), 8.0, 114, N'Soft gray table lamp for bedside or console styling sourced as a distinct luxury catalog image so the collection no longer repeats near-identical product photos.', N'NCC004', 24, N'Warm white', N'Metal fixture, warm LED-compatible light', N'Fixture or table-lamp scale', N'12 tháng', N'Luxury Showroom'),
        (63, N'Classic Sculpted Table Lamp', N'classic-sculpted-table-lamp', 17, N'Classic sculpted premium table lamp', 3190000.0, N'lux-classic-table-lamp.jpg', CAST('2026-08-13' AS datetime), 0.0, 121, N'Classic sculpted table lamp with premium accent presence sourced as a distinct luxury catalog image so the collection no longer repeats near-identical product photos.', N'NCC003', 27, N'Ceramic accent', N'Ceramic or metal decorative object', N'Statement decor scale', N'24 tháng', N'Luxury Showroom'),
        (64, N'Floral Ceramic Vase', N'floral-ceramic-vase', 17, N'Floral ceramic vase for shelves', 1590000.0, N'lux-ceramic-vase-floral.jpg', CAST('2026-08-14' AS datetime), 6.0, 128, N'Floral ceramic vase for elegant shelf and console decor sourced as a distinct luxury catalog image so the collection no longer repeats near-identical product photos.', N'NCC003', 6, N'Ceramic accent', N'Ceramic or metal decorative object', N'Statement decor scale', N'12 tháng', N'Luxury Showroom'),
        (65, N'Architectural Succulent Planter', N'architectural-succulent-planter', 9, N'Modern planter with structured greenery', 890000.0, N'lux-modern-room-succulent.jpg', CAST('2026-08-15' AS datetime), 0.0, 45, N'Modern planter with structured greenery in a premium setting sourced as a distinct luxury catalog image so the collection no longer repeats near-identical product photos.', N'NCC003', 9, N'Green', N'Ceramic planter, botanical greenery', N'Tabletop accent size', N'12 tháng', N'Luxury Showroom'),
        (66, N'Ray Lounge Chair', N'ray-lounge-chair', 1, N'Sculptural reading lounge chair', 6890000.0, N'lux-ray-lounge-chair.jpg', CAST('2026-08-16' AS datetime), 0.0, 52, N'Sculptural lounge chair for statement reading corners sourced as a distinct luxury catalog image so the collection no longer repeats near-identical product photos.', N'NCC001', 12, N'Warm neutral', N'Premium upholstery, hardwood frame', N'Living-room scale', N'24 tháng', N'Luxury Showroom'),
        (67, N'Walnut Storage Interior', N'walnut-storage-interior', 7, N'Warm wood architectural storage', 5290000.0, N'lux-duncan-storage-interior.jpg', CAST('2026-08-17' AS datetime), 5.0, 59, N'Warm wood storage interior with architectural modern styling sourced as a distinct luxury catalog image so the collection no longer repeats near-identical product photos.', N'NCC002', 15, N'Walnut', N'Wood cabinetry, architectural storage', N'Storage wall / console scale', N'24 tháng', N'Luxury Showroom'),
        (68, N'Heritage Map Wall Art', N'heritage-map-wall-art', 18, N'Large framed map artwork for interiors', 2490000.0, N'lux-framed-map-wall-art.jpg', CAST('2026-08-18' AS datetime), 8.0, 66, N'Large-format framed map artwork for refined interior walls sourced as a distinct luxury catalog image so the collection no longer repeats near-identical product photos.', N'NCC003', 18, N'Multi', N'Printed art paper, slim frame', N'Approx. 70 x 100 cm', N'12 tháng', N'Luxury Showroom');
    SET IDENTITY_INSERT dbo.HangHoa OFF;

    MERGE dbo.KhachHang AS target
    USING (VALUES
        (N'admin', N'Administrator', CAST(1 AS bit), CAST('1990-01-01' AS datetime), N'Admin Address', N'0900000000', N'admin@hshop.local', N'Photo.gif', N'52968bfa80ccf71df5e1dc38df716666', N'A1B2C3', CAST(1 AS bit), 1)
    ) AS src (MaKH, HoTen, GioiTinh, NgaySinh, DiaChi, DienThoai, Email, Hinh, MatKhau, RandomKey, HieuLuc, VaiTro)
    ON target.MaKH = src.MaKH
    WHEN MATCHED THEN UPDATE SET HoTen=src.HoTen, GioiTinh=src.GioiTinh, NgaySinh=src.NgaySinh, DiaChi=src.DiaChi, DienThoai=src.DienThoai, Email=src.Email, Hinh=src.Hinh, MatKhau=src.MatKhau, RandomKey=src.RandomKey, HieuLuc=src.HieuLuc, VaiTro=src.VaiTro
    WHEN NOT MATCHED BY TARGET THEN INSERT (MaKH, HoTen, GioiTinh, NgaySinh, DiaChi, DienThoai, Email, Hinh, MatKhau, RandomKey, HieuLuc, VaiTro) VALUES (src.MaKH, src.HoTen, src.GioiTinh, src.NgaySinh, src.DiaChi, src.DienThoai, src.Email, src.Hinh, src.MatKhau, src.RandomKey, src.HieuLuc, src.VaiTro);

    UPDATE c SET DonGia = h.DonGia
    FROM dbo.ChiTietHD c
    INNER JOIN dbo.HangHoa h ON h.MaHH = c.MaHH;

    COMMIT TRAN;
    SELECT N'[SEED_OK]' AS Msg, 'Loai' AS Tbl, COUNT(*) AS Cnt FROM dbo.Loai
    UNION ALL SELECT N'[SEED_OK]', 'NhaCungCap', COUNT(*) FROM dbo.NhaCungCap
    UNION ALL SELECT N'[SEED_OK]', 'TrangThai', COUNT(*) FROM dbo.TrangThai
    UNION ALL SELECT N'[SEED_OK]', 'HangHoa', COUNT(*) FROM dbo.HangHoa
    UNION ALL SELECT N'[SEED_OK]', 'KhachHang', COUNT(*) FROM dbo.KhachHang
    UNION ALL SELECT N'[SEED_OK]', 'LuxuryWebImages', COUNT(*) FROM dbo.HangHoa WHERE Hinh LIKE N'lux-%';
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRAN;
    DECLARE @Err NVARCHAR(4000) = ERROR_MESSAGE();
    RAISERROR(N'Seed failed: %s', 16, 1, @Err);
END CATCH;
